// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Country struct {
	ID        uuid.UUID
	Name      string
	Code      string
	RegionID  uuid.UUID
	CreatedAt time.Time
}

type Pool struct {
	ID        uuid.UUID
	Tag       string
	RegionID  uuid.UUID
	Subdomain string
	Port      int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PoolUpstreamWeight struct {
	ID         uuid.UUID
	PoolID     uuid.UUID
	UpstreamID uuid.UUID
	Weight     int32
}

type Region struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Upstream struct {
	ID               uuid.UUID
	Tag              string
	UpstreamProvider string
	Format           string
	Port             int32
	Domain           string
	CreatedAt        time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserIpWhitelist struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	IpCidr    string
	CreatedAt time.Time
}

type UserPool struct {
	ID        uuid.UUID
	PoolID    uuid.UUID
	UserID    uuid.UUID
	DataLimit int64
	DataUsage int64
}

type Worker struct {
	ID        uuid.UUID
	Name      string
	RegionID  uuid.UUID
	IpAddress string
	Port      int32
	Status    string
	PoolID    uuid.UUID
	LastSeen  time.Time
	CreatedAt time.Time
}

type WorkerDomain struct {
	ID       uuid.UUID
	WorkerID uuid.UUID
	Domain   string
}
