// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Country struct {
	ID        uuid.UUID
	Name      string
	Code      string
	RegionID  uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Pool struct {
	ID        uuid.UUID
	Name      string
	Tag       sql.NullString
	RegionID  uuid.NullUUID
	Subdomain sql.NullString
	Port      int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PoolUpstreamWeight struct {
	ID         uuid.UUID
	PoolID     uuid.UUID
	UpstreamID uuid.UUID
	Weight     int32
}

type Region struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Upstream struct {
	ID        uuid.UUID
	Format    string
	Port      int32
	Domain    string
	PoolID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     sql.NullString
	Username  string
	Password  string
	DataLimit int64
	DataUsage int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserIpWhitelist struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	IpCidr    string
	CreatedAt sql.NullTime
}

type UserPool struct {
	ID     uuid.UUID
	PoolID uuid.UUID
	UserID uuid.UUID
}

type Worker struct {
	ID        uuid.UUID
	Name      string
	RegionID  uuid.UUID
	IpAddress string
	Status    sql.NullString
	LastSeen  sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type WorkerDomain struct {
	ID       uuid.UUID
	WorkerID uuid.UUID
	Domain   string
}
