// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pools.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addCountry = `-- name: AddCountry :one
INSERT INTO country(name,code,region_id)
VALUES($1,$2,$3)
RETURNING id, name, code, region_id, created_at, updated_at
`

type AddCountryParams struct {
	Name     string
	Code     string
	RegionID uuid.UUID
}

func (q *Queries) AddCountry(ctx context.Context, arg AddCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, addCountry, arg.Name, arg.Code, arg.RegionID)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.RegionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addRegion = `-- name: AddRegion :one
INSERT INTO region(name)
VALUES($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) AddRegion(ctx context.Context, name string) (Region, error) {
	row := q.db.QueryRowContext(ctx, addRegion, name)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addUpstream = `-- name: AddUpstream :one
INSERT INTO upstream(upstream_provider,format,port,domain,pool_id)
VALUES($1,$2,$3,$4,$5)
RETURNING id, upstream_provider, format, port, domain, pool_id, created_at, updated_at
`

type AddUpstreamParams struct {
	UpstreamProvider string
	Format           string
	Port             int32
	Domain           string
	PoolID           uuid.UUID
}

func (q *Queries) AddUpstream(ctx context.Context, arg AddUpstreamParams) (Upstream, error) {
	row := q.db.QueryRowContext(ctx, addUpstream,
		arg.UpstreamProvider,
		arg.Format,
		arg.Port,
		arg.Domain,
		arg.PoolID,
	)
	var i Upstream
	err := row.Scan(
		&i.ID,
		&i.UpstreamProvider,
		&i.Format,
		&i.Port,
		&i.Domain,
		&i.PoolID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM country as c
where c.name = $1
RETURNING id, name, code, region_id, created_at, updated_at
`

func (q *Queries) DeleteCountry(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCountry, name)
	return err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM region as r
where r.name = $1
RETURNING id, name, created_at, updated_at
`

func (q *Queries) DeleteRegion(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRegion, name)
	return err
}

const deleteUpstream = `-- name: DeleteUpstream :exec
DELETE FROM upstream as u
where u.id = $1
RETURNING id, upstream_provider, format, port, domain, pool_id, created_at, updated_at
`

func (q *Queries) DeleteUpstream(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUpstream, id)
	return err
}

const getCountries = `-- name: GetCountries :many
SELECT id, name, code, region_id, created_at, updated_at FROM country
`

func (q *Queries) GetCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, getCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.RegionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegions = `-- name: GetRegions :many
SELECT id, name, created_at, updated_at FROM region
`

func (q *Queries) GetRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, getRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpstreams = `-- name: GetUpstreams :many
SELECT id, upstream_provider, format, port, domain, pool_id, created_at, updated_at FROM upstream
`

func (q *Queries) GetUpstreams(ctx context.Context) ([]Upstream, error) {
	rows, err := q.db.QueryContext(ctx, getUpstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upstream
	for rows.Next() {
		var i Upstream
		if err := rows.Scan(
			&i.ID,
			&i.UpstreamProvider,
			&i.Format,
			&i.Port,
			&i.Domain,
			&i.PoolID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
