// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pools.sql

package repository

import (
	"context"

	"github.com/lib/pq"
)

const getPoolsbyTags = `-- name: GetPoolsbyTags :many
SELECT id, name, tag, region_id, subdomain, port, created_at, updated_at FROM pool
WHERE pool.tag = ANY($1::text[])
`

func (q *Queries) GetPoolsbyTags(ctx context.Context, dollar_1 []string) ([]Pool, error) {
	rows, err := q.db.QueryContext(ctx, getPoolsbyTags, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pool
	for rows.Next() {
		var i Pool
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.RegionID,
			&i.Subdomain,
			&i.Port,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
