// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPoolsbyTags(ctx context.Context, dollar_1 []string) ([]Pool, error)
	InsertUserIpwhitelist(ctx context.Context, arg InsertUserIpwhitelistParams) (UserIpWhitelist, error)
	InsertUserPool(ctx context.Context, arg InsertUserPoolParams) (UserPool, error)
}

var _ Querier = (*Queries)(nil)
