// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user"(email,username,password,data_limit)
VALUES ($1,$2,$3,$4)
RETURNING id, email, username, password, data_limit, data_usage, status, created_at, updated_at
`

type CreateUserParams struct {
	Email     sql.NullString
	Username  string
	Password  string
	DataLimit int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.DataLimit,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DataLimit,
		&i.DataUsage,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllusers = `-- name: GetAllusers :many
SELECT 
    u.id,
    u.username,
    u.password,
    u.data_usage,
    u.email,
    u.status,
    u.data_limit,
    u.created_at,
    u.updated_at,
    COALESCE(ARRAY_AGG(DISTINCT iw.ip_cidr) FILTER (WHERE iw.ip_cidr IS NOT NULL), '{}')::text[] AS ip_whitelist,
    COALESCE(ARRAY_AGG(DISTINCT p.name) FILTER (WHERE p.name IS NOT NULL), '{}')::text[] AS pools
FROM "user" AS u
LEFT JOIN user_ip_whitelist AS iw ON u.id = iw.user_id
LEFT JOIN user_pools AS up ON u.id = up.user_id
LEFT JOIN pool AS p ON up.pool_id = p.id
GROUP BY u.id
`

type GetAllusersRow struct {
	ID          uuid.UUID
	Username    string
	Password    string
	DataUsage   int64
	Email       sql.NullString
	Status      string
	DataLimit   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IpWhitelist []string
	Pools       []string
}

func (q *Queries) GetAllusers(ctx context.Context) ([]GetAllusersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllusers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllusersRow
	for rows.Next() {
		var i GetAllusersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.DataUsage,
			&i.Email,
			&i.Status,
			&i.DataLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.IpWhitelist),
			pq.Array(&i.Pools),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatausageById = `-- name: GetDatausageById :one
SELECT u.data_limit,u.data_usage FROM "user" as u
WHERE u.id = $1
`

type GetDatausageByIdRow struct {
	DataLimit int64
	DataUsage int64
}

func (q *Queries) GetDatausageById(ctx context.Context, id uuid.UUID) (GetDatausageByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDatausageById, id)
	var i GetDatausageByIdRow
	err := row.Scan(&i.DataLimit, &i.DataUsage)
	return i, err
}

const getUserPoolsByUserId = `-- name: GetUserPoolsByUserId :one
select u.id,COALESCE(ARRAY_AGG(DISTINCT up.pool_id) FILTER (WHERE up.pool_id IS NOT NULL),'{}')::TEXT[] from  "user" as u
full join user_pools as up
on u.id = up.user_id
WHERE u.id = $1
group by u.id
`

type GetUserPoolsByUserIdRow struct {
	ID      uuid.NullUUID
	Column2 []string
}

func (q *Queries) GetUserPoolsByUserId(ctx context.Context, id uuid.UUID) (GetUserPoolsByUserIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPoolsByUserId, id)
	var i GetUserPoolsByUserIdRow
	err := row.Scan(&i.ID, pq.Array(&i.Column2))
	return i, err
}

const getUserbyId = `-- name: GetUserbyId :one
SELECT 
    u.id,
    u.username,
    u.password,
    u.data_usage,
    u.email,
    u.status,
    u.data_limit,
    u.created_at,
    u.updated_at,
    COALESCE(ARRAY_AGG(DISTINCT iw.ip_cidr) FILTER (WHERE iw.ip_cidr IS NOT NULL), '{}')::text[] AS ip_whitelist,
    COALESCE(ARRAY_AGG(DISTINCT p.name) FILTER (WHERE p.name IS NOT NULL), '{}')::text[] AS pools
FROM "user" AS u
LEFT JOIN user_ip_whitelist AS iw ON u.id = iw.user_id
LEFT JOIN user_pools AS up ON u.id = up.user_id
LEFT JOIN pool AS p ON up.pool_id = p.id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserbyIdRow struct {
	ID          uuid.UUID
	Username    string
	Password    string
	DataUsage   int64
	Email       sql.NullString
	Status      string
	DataLimit   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IpWhitelist []string
	Pools       []string
}

func (q *Queries) GetUserbyId(ctx context.Context, id uuid.UUID) (GetUserbyIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserbyId, id)
	var i GetUserbyIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.DataUsage,
		&i.Email,
		&i.Status,
		&i.DataLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.IpWhitelist),
		pq.Array(&i.Pools),
	)
	return i, err
}

const insertUserIpwhitelist = `-- name: InsertUserIpwhitelist :many
INSERT INTO user_ip_whitelist(user_id,ip_cidr)
SELECT $1, UNNEST($2::text[])
RETURNING id, user_id, ip_cidr, created_at
`

type InsertUserIpwhitelistParams struct {
	UserID  uuid.UUID
	Column2 []string
}

func (q *Queries) InsertUserIpwhitelist(ctx context.Context, arg InsertUserIpwhitelistParams) ([]UserIpWhitelist, error) {
	rows, err := q.db.QueryContext(ctx, insertUserIpwhitelist, arg.UserID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIpWhitelist
	for rows.Next() {
		var i UserIpWhitelist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IpCidr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserPool = `-- name: InsertUserPool :many
INSERT INTO user_pools(user_id,pool_id)
SELECT $1, UNNEST($2::uuid[])
RETURNING id, pool_id, user_id
`

type InsertUserPoolParams struct {
	UserID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) InsertUserPool(ctx context.Context, arg InsertUserPoolParams) ([]UserPool, error) {
	rows, err := q.db.QueryContext(ctx, insertUserPool, arg.UserID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPool
	for rows.Next() {
		var i UserPool
		if err := rows.Scan(&i.ID, &i.PoolID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE "user" 
SET 
status = 'deleted',
updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user" 
SET 
email = COALESCE($2,email), 
data_limit = COALESCE($3,data_limit), 
status = COALESCE($4,status),
updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, username, password, data_limit, data_usage, status, created_at, updated_at
`

type UpdateUserParams struct {
	ID        uuid.UUID
	Email     sql.NullString
	DataLimit sql.NullInt64
	Status    sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DataLimit,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DataLimit,
		&i.DataUsage,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeUserPool = `-- name: removeUserPool :exec
DELETE FROM user_pools as up
WHERE up.user_id = $1
`

func (q *Queries) removeUserPool(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeUserPool, userID)
	return err
}
