// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user"(id,email,username,password,data_limit)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, email, username, password, data_limit, data_usage, status, created_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID
	Email     sql.NullString
	Username  string
	Password  string
	DataLimit int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.DataLimit,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DataLimit,
		&i.DataUsage,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
