// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addUserPoolsByPoolTags = `-- name: AddUserPoolsByPoolTags :one
WITH matching_pools AS (
    SELECT id, tag
    FROM pool 
    WHERE tag = ANY($2::text[])
), 
inserted_rows AS (
    INSERT INTO user_pools (user_id, pool_id,data_limit)
    SELECT $1, id,UNNEST($3::BIGINT[]) FROM matching_pools
    ON CONFLICT (user_id, pool_id) DO NOTHING
    RETURNING pool_id, user_id,data_limit
)
SELECT 
    i.user_id, 
    COALESCE(ARRAY_AGG(p.tag), '{}')::TEXT[] AS inserted_tags,
    COALESCE(ARRAY_AGG(i.data_limit), '{}')::BIGINT[] AS inserted_data_limits
FROM inserted_rows i
JOIN matching_pools p ON i.pool_id = p.id
GROUP BY i.user_id
`

type AddUserPoolsByPoolTagsParams struct {
	UserID     uuid.UUID
	Tags       []string
	DataLimits []int64
}

type AddUserPoolsByPoolTagsRow struct {
	UserID             uuid.UUID
	InsertedTags       []string
	InsertedDataLimits []int64
}

func (q *Queries) AddUserPoolsByPoolTags(ctx context.Context, arg AddUserPoolsByPoolTagsParams) (AddUserPoolsByPoolTagsRow, error) {
	row := q.db.QueryRowContext(ctx, addUserPoolsByPoolTags, arg.UserID, pq.Array(arg.Tags), pq.Array(arg.DataLimits))
	var i AddUserPoolsByPoolTagsRow
	err := row.Scan(&i.UserID, pq.Array(&i.InsertedTags), pq.Array(&i.InsertedDataLimits))
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user"(username,password)
VALUES ($1,$2)
RETURNING id, username, password, status, created_at, updated_at
`

type CreateUserParams struct {
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserIpwhitelist = `-- name: DeleteUserIpwhitelist :execresult
DELETE FROM user_ip_whitelist
WHERE user_id = $1
  AND ip_cidr = ANY($2::TEXT[])
`

type DeleteUserIpwhitelistParams struct {
	UserID  uuid.UUID
	Column2 []string
}

func (q *Queries) DeleteUserIpwhitelist(ctx context.Context, arg DeleteUserIpwhitelistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserIpwhitelist, arg.UserID, pq.Array(arg.Column2))
}

const deleteUserPoolsByTags = `-- name: DeleteUserPoolsByTags :execresult
DELETE FROM user_pools
WHERE user_id = $1
  AND pool_id IN (
      SELECT id 
      FROM pool 
      WHERE tag = ANY($2::text[]) 
  )
`

type DeleteUserPoolsByTagsParams struct {
	UserID  uuid.UUID
	Column2 []string
}

func (q *Queries) DeleteUserPoolsByTags(ctx context.Context, arg DeleteUserPoolsByTagsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserPoolsByTags, arg.UserID, pq.Array(arg.Column2))
}

const generateproxyString = `-- name: GenerateproxyString :one
SELECT p.tag,p.subdomain,p.port,u.username,u.password FROM pool as p
join region as r on p.region_id = r.id
join country as c on r.id = c.region_id
join user_pools as up on p.id = up.pool_id
join "user" as u on up.user_id = u.id
where c.code = $1 AND p.tag LIKE $2 AND up.user_id = $3
`

type GenerateproxyStringParams struct {
	Code   string
	Tag    string
	UserID uuid.UUID
}

type GenerateproxyStringRow struct {
	Tag       string
	Subdomain string
	Port      int32
	Username  string
	Password  string
}

func (q *Queries) GenerateproxyString(ctx context.Context, arg GenerateproxyStringParams) (GenerateproxyStringRow, error) {
	row := q.db.QueryRowContext(ctx, generateproxyString, arg.Code, arg.Tag, arg.UserID)
	var i GenerateproxyStringRow
	err := row.Scan(
		&i.Tag,
		&i.Subdomain,
		&i.Port,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getAllusers = `-- name: GetAllusers :many
SELECT 
    u.id,
    u.username,
    u.password,
    u.status,
    u.created_at,
    u.updated_at,
    COALESCE(ARRAY_AGG(DISTINCT iw.ip_cidr) FILTER (WHERE iw.ip_cidr IS NOT NULL), '{}')::text[] AS ip_whitelist,
    COALESCE(ARRAY_AGG(DISTINCT p.tag) FILTER (WHERE p.tag IS NOT NULL), '{}')::text[] AS pools
FROM "user" AS u
LEFT JOIN user_ip_whitelist AS iw ON u.id = iw.user_id
LEFT JOIN user_pools AS up ON u.id = up.user_id
LEFT JOIN pool AS p ON up.pool_id = p.id
GROUP BY u.id
`

type GetAllusersRow struct {
	ID          uuid.UUID
	Username    string
	Password    string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IpWhitelist []string
	Pools       []string
}

func (q *Queries) GetAllusers(ctx context.Context) ([]GetAllusersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllusers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllusersRow
	for rows.Next() {
		var i GetAllusersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.IpWhitelist),
			pq.Array(&i.Pools),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatausageById = `-- name: GetDatausageById :many
SELECT up.data_limit,up.data_usage,p.tag AS pool_tag 
FROM user_pools AS up 
INNER JOIN pool AS p ON up.pool_id = p.id
WHERE up.user_id = $1
`

type GetDatausageByIdRow struct {
	DataLimit int64
	DataUsage int64
	PoolTag   string
}

func (q *Queries) GetDatausageById(ctx context.Context, userID uuid.UUID) ([]GetDatausageByIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getDatausageById, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDatausageByIdRow
	for rows.Next() {
		var i GetDatausageByIdRow
		if err := rows.Scan(&i.DataLimit, &i.DataUsage, &i.PoolTag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, status, created_at, updated_at
FROM "user"
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIpwhitelistByUserId = `-- name: GetUserIpwhitelistByUserId :one
SELECT 
    COALESCE(
        ARRAY_AGG(DISTINCT w.ip_cidr) FILTER (WHERE w.ip_cidr IS NOT NULL), 
        '{}'
    )::TEXT[] AS ip_list
FROM "user" u                       
LEFT JOIN user_ip_whitelist w      
    ON u.id = w.user_id
WHERE u.id = $1
GROUP BY u.id
`

func (q *Queries) GetUserIpwhitelistByUserId(ctx context.Context, id uuid.UUID) ([]string, error) {
	row := q.db.QueryRowContext(ctx, getUserIpwhitelistByUserId, id)
	var ip_list []string
	err := row.Scan(pq.Array(&ip_list))
	return ip_list, err
}

const getUserPoolsByUserId = `-- name: GetUserPoolsByUserId :one
select u.id,
    COALESCE(ARRAY_AGG(DISTINCT p.tag) FILTER (WHERE p.tag IS NOT NULL),'{}')::TEXT[] as pool_tags
from  "user" as u
left join user_pools as up
on u.id = up.user_id
left join pool as p
on up.pool_id = p.id
WHERE u.id = $1
group by u.id
`

type GetUserPoolsByUserIdRow struct {
	ID       uuid.UUID
	PoolTags []string
}

func (q *Queries) GetUserPoolsByUserId(ctx context.Context, id uuid.UUID) (GetUserPoolsByUserIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPoolsByUserId, id)
	var i GetUserPoolsByUserIdRow
	err := row.Scan(&i.ID, pq.Array(&i.PoolTags))
	return i, err
}

const getUserbyId = `-- name: GetUserbyId :one
SELECT 
    u.id,
    u.username,
    u.password,
    u.status,
    u.created_at,
    u.updated_at,
    COALESCE(ARRAY_AGG(DISTINCT iw.ip_cidr) FILTER (WHERE iw.ip_cidr IS NOT NULL), '{}')::text[] AS ip_whitelist,
    COALESCE(ARRAY_AGG(DISTINCT p.tag) FILTER (WHERE p.tag IS NOT NULL), '{}')::text[] AS pools
FROM "user" AS u
LEFT JOIN user_ip_whitelist AS iw ON u.id = iw.user_id
LEFT JOIN user_pools AS up ON u.id = up.user_id
LEFT JOIN pool AS p ON up.pool_id = p.id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserbyIdRow struct {
	ID          uuid.UUID
	Username    string
	Password    string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IpWhitelist []string
	Pools       []string
}

func (q *Queries) GetUserbyId(ctx context.Context, id uuid.UUID) (GetUserbyIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserbyId, id)
	var i GetUserbyIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.IpWhitelist),
		pq.Array(&i.Pools),
	)
	return i, err
}

const insertUserIpwhitelist = `-- name: InsertUserIpwhitelist :one
WITH inserted AS (
    INSERT INTO user_ip_whitelist (user_id, ip_cidr)
    SELECT $1,UNNEST($2::text[])
    RETURNING ip_cidr
)
SELECT 
$1::UUID AS user_id,
ARRAY_AGG(ip_cidr)::TEXT[] AS ip_whitelist FROM inserted
`

type InsertUserIpwhitelistParams struct {
	UserID      uuid.UUID
	IpWhitelist []string
}

type InsertUserIpwhitelistRow struct {
	UserID      uuid.UUID
	IpWhitelist []string
}

func (q *Queries) InsertUserIpwhitelist(ctx context.Context, arg InsertUserIpwhitelistParams) (InsertUserIpwhitelistRow, error) {
	row := q.db.QueryRowContext(ctx, insertUserIpwhitelist, arg.UserID, pq.Array(arg.IpWhitelist))
	var i InsertUserIpwhitelistRow
	err := row.Scan(&i.UserID, pq.Array(&i.IpWhitelist))
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user" 
SET 
status = COALESCE($2,status),
updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, username, password, status, created_at, updated_at
`

type UpdateUserParams struct {
	ID     uuid.UUID
	Status sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
