// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addWorkerDomain = `-- name: AddWorkerDomain :one
INSERT INTO worker_domains (worker_id, domain)
VALUES ((SELECT id FROM worker WHERE name = $1), UNNEST($2::TEXT[]))
RETURNING id, worker_id, domain
`

type AddWorkerDomainParams struct {
	Name    string
	Column2 []string
}

func (q *Queries) AddWorkerDomain(ctx context.Context, arg AddWorkerDomainParams) (WorkerDomain, error) {
	row := q.db.QueryRowContext(ctx, addWorkerDomain, arg.Name, pq.Array(arg.Column2))
	var i WorkerDomain
	err := row.Scan(&i.ID, &i.WorkerID, &i.Domain)
	return i, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (name, region_id, ip_address)
VALUES ($1,(SELECT id from region where region.name = $2), $3)
RETURNING id, name, region_id, ip_address, port, status, pool_id, last_seen, created_at
`

type CreateWorkerParams struct {
	Name      string
	Name_2    string
	IpAddress string
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker, arg.Name, arg.Name_2, arg.IpAddress)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.IpAddress,
		&i.Port,
		&i.Status,
		&i.PoolID,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkerByName = `-- name: DeleteWorkerByName :exec
DELETE FROM worker WHERE name = $1
`

func (q *Queries) DeleteWorkerByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkerByName, name)
	return err
}

const deleteWorkerDomain = `-- name: DeleteWorkerDomain :exec
DELETE FROM worker_domains
WHERE worker_id = (SELECT id FROM worker WHERE name = $1) AND domain = ANY($2::TEXT[])
`

type DeleteWorkerDomainParams struct {
	Name    string
	Column2 []string
}

func (q *Queries) DeleteWorkerDomain(ctx context.Context, arg DeleteWorkerDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkerDomain, arg.Name, pq.Array(arg.Column2))
	return err
}

const getAllWorkers = `-- name: GetAllWorkers :many
SELECT 
    w.id, 
    w.name, 
    w.ip_address, 
    w.status, 
    w.last_seen, 
    w.created_at, 
    r.name AS region_name,
    COALESCE(array_agg(wd.domain) FILTER (WHERE wd.domain IS NOT NULL), '{}')::text[] AS domains
FROM worker w
JOIN region r ON w.region_id = r.id
LEFT JOIN worker_domains wd ON w.id = wd.worker_id
GROUP BY w.id, r.name
`

type GetAllWorkersRow struct {
	ID         uuid.UUID
	Name       string
	IpAddress  string
	Status     string
	LastSeen   time.Time
	CreatedAt  time.Time
	RegionName string
	Domains    []string
}

func (q *Queries) GetAllWorkers(ctx context.Context) ([]GetAllWorkersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWorkersRow
	for rows.Next() {
		var i GetAllWorkersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IpAddress,
			&i.Status,
			&i.LastSeen,
			&i.CreatedAt,
			&i.RegionName,
			pq.Array(&i.Domains),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkerByName = `-- name: GetWorkerByName :one
SELECT 
    w.id, 
    w.name, 
    w.ip_address, 
    w.status, 
    w.last_seen, 
    w.created_at, 
    r.name AS region_name,
    COALESCE(array_agg(wd.domain) FILTER (WHERE wd.domain IS NOT NULL), '{}')::text[] AS domains
FROM worker w
JOIN region r ON w.region_id = r.id
LEFT JOIN worker_domains wd ON w.id = wd.worker_id
WHERE w.name = $1
GROUP BY w.id, r.name
`

type GetWorkerByNameRow struct {
	ID         uuid.UUID
	Name       string
	IpAddress  string
	Status     string
	LastSeen   time.Time
	CreatedAt  time.Time
	RegionName string
	Domains    []string
}

func (q *Queries) GetWorkerByName(ctx context.Context, name string) (GetWorkerByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByName, name)
	var i GetWorkerByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IpAddress,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.RegionName,
		pq.Array(&i.Domains),
	)
	return i, err
}
