// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package repository

import (
	"context"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (name, region_id, ip_address)
VALUES ($1,(SELECT id from region where region.name = $2), $3)
RETURNING id, name, region_id, ip_address, status, last_seen, created_at, updated_at
`

type CreateWorkerParams struct {
	Name      string
	Name_2    string
	IpAddress string
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker, arg.Name, arg.Name_2, arg.IpAddress)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.IpAddress,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
