// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddCountry(ctx context.Context, arg AddCountryParams) (Country, error)
	AddPoolUpstreamWeight(ctx context.Context, arg AddPoolUpstreamWeightParams) (PoolUpstreamWeight, error)
	AddRegion(ctx context.Context, name string) (Region, error)
	AddUpstream(ctx context.Context, arg AddUpstreamParams) (Upstream, error)
	AddUserPoolsByPoolTags(ctx context.Context, arg AddUserPoolsByPoolTagsParams) (AddUserPoolsByPoolTagsRow, error)
	AddWorkerDomain(ctx context.Context, arg AddWorkerDomainParams) (WorkerDomain, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error)
	DeleteCountry(ctx context.Context, name string) error
	DeletePool(ctx context.Context, tag string) (sql.Result, error)
	DeletePoolUpstreamWeight(ctx context.Context, arg DeletePoolUpstreamWeightParams) (sql.Result, error)
	DeleteRegion(ctx context.Context, name string) error
	DeleteUpstreamByTag(ctx context.Context, tag string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserIpwhitelist(ctx context.Context, arg DeleteUserIpwhitelistParams) (sql.Result, error)
	DeleteUserPoolsByTags(ctx context.Context, arg DeleteUserPoolsByTagsParams) (sql.Result, error)
	DeleteWorkerByName(ctx context.Context, name string) (sql.Result, error)
	DeleteWorkerDomain(ctx context.Context, arg DeleteWorkerDomainParams) (sql.Result, error)
	GenerateproxyString(ctx context.Context, arg GenerateproxyStringParams) (GenerateproxyStringRow, error)
	GetAllWorkers(ctx context.Context) ([]GetAllWorkersRow, error)
	GetAllusers(ctx context.Context) ([]GetAllusersRow, error)
	GetCountries(ctx context.Context) ([]Country, error)
	GetDatausageById(ctx context.Context, userID uuid.UUID) ([]GetDatausageByIdRow, error)
	GetPoolByTagWithUpstreams(ctx context.Context, tag string) ([]GetPoolByTagWithUpstreamsRow, error)
	GetRegions(ctx context.Context) ([]Region, error)
	GetUpstreams(ctx context.Context) ([]Upstream, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserIpwhitelistByUserId(ctx context.Context, id uuid.UUID) ([]string, error)
	GetUserPoolsByUserId(ctx context.Context, id uuid.UUID) (GetUserPoolsByUserIdRow, error)
	GetUserbyId(ctx context.Context, id uuid.UUID) (GetUserbyIdRow, error)
	GetWorkerById(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetWorkerByName(ctx context.Context, name string) (GetWorkerByNameRow, error)
	GetWorkerPoolConfig(ctx context.Context, id uuid.UUID) ([]GetWorkerPoolConfigRow, error)
	InsertPoolUpstreamWeight(ctx context.Context, arg InsertPoolUpstreamWeightParams) ([]PoolUpstreamWeight, error)
	InsertUserIpwhitelist(ctx context.Context, arg InsertUserIpwhitelistParams) (InsertUserIpwhitelistRow, error)
	InsetPool(ctx context.Context, arg InsetPoolParams) (Pool, error)
	ListPoolsWithUpstreams(ctx context.Context) ([]ListPoolsWithUpstreamsRow, error)
	UpdatePool(ctx context.Context, arg UpdatePoolParams) (Pool, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWorkerLastSeen(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
